# Generated by Django 4.2.7 on 2024-02-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=100)),
                ("emp_id", models.CharField(max_length=200)),
                ("phone", models.IntegerField(max_length=20)),
                ("working", models.BooleanField(default=True)),
                ("address", models.CharField(max_length=150)),
                ("department", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(name="Student",),
    ]
