# Generated by Django 4.2.7 on 2024-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_emp_delete_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp", name="working", field=models.BooleanField(default=False),
        ),
    ]
